name: CI

on: [push]
#on:
#  schedule:
#  # run every at 21:00 UTC
#  - cron: "0 21 * * *"

jobs:
  daily_build:
    runs-on: ubuntu-latest
    env:
      COMMIT_AUTHOR: Daily Deploy GitHub Workflow
      COMMIT_AUTHOR_EMAIL: deploy@github-actions.org
    steps:
    - uses: actions/checkout@v1
    - name: Install prerequisites
      run: pip install --upgrade wheel setuptools
    - name: Display the path
      shell: python
      run: |
        import os
        print(os.environ['PATH'])
    - name: Install
      run: |
        echo "::add-path::/home/runner/.local/bin"
        pip install -e . -v
    - name: fetch metadata
      run: |
        echo "::add-path::/home/runner/.local/bin"
        aiida-registry fetch
    - name: make pages
      run: |
        echo "::add-path::/home/runner/.local/bin"
        aiida-registry html
    - name: deploy
      run: ./.github/deploy.sh
